### ISSUE TITLE
Why escaping HTML?

### ISSUE THREAD

**Issue by tallesl** [evilstreak/markdown-js#219]
[Why?](https://github.com/evilstreak/markdown-js/blob/84579a01d9af4b63d7f897dd542ccf1fb596be82/src/render_tree.js#L91)

Shouldn't markdown leave those alone?

Both [Gruber's](http://daringfireball.net/projects/markdown/dingus) and [Common Mark](http://jgm.github.io/stmd/js/) implementations seems to leave it alone.

I'm using some HTML content in my markdown files, this behavior is preventing me to use this module.

**Comment by dongli** [comment]
I am also using `marked` now, since it automatically escapes HTML inside Markdown.
