### ISSUE TITLE
Code type shows up in the html

### ISSUE THREAD

**Issue by franzwong** [evilstreak/markdown-js#239]
I would like to define a code block with code type (e.g. html, javascript, etc). I don't expect the type will be shown in the output html.

`````` javascript
markdown.toHTML('```javascript\nconsole.log("hello");\n```');
``````

Expect:

``` html
<p><code>
console.log(&quot;hello&quot;);
</code></p>
```

Actual:

``` html
<p><code>javascript
console.log(&quot;hello&quot;);
</code></p>
```

**Comment by coltonTB** [comment]
I switched to https://github.com/chjj/marked - better implementation that addresses this issue
