### ISSUE TITLE
QML compatible version

### ISSUE THREAD

**Issue by anion155** [evilstreak/markdown-js#265]
Qml [is](http://doc.qt.io/qt-5/qmlreference.html)
[Here](doc.qt.io/qt-5/qtqml-javascript-resources.html) is example of how you can import js library in to qml

**Comment by clz619** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
