### ISSUE TITLE
multiple linebreaks

### ISSUE THREAD

**Issue by ErrorPro** [evilstreak/markdown-js#278]
Hey, i want to put some line breaks into my markdown. Im trying to do it like this:

```
hello \n\n\n\n\n multiple
```

or like this:

```
hello <br /> <br /> <br /> multiple
```

Neither works. How can i do it?

**Comment by alschofield** [comment]
ErrorPro, did anything come from this issue? im coming across the same issue, maybe there is just a different syntactic way of rendering the new lines?

**Comment by ashb** [comment]
If you put two tailing spaces at the end of the line (`"hello  \nline"`) this will be turned into a `<br>` in the HTML output. Multiple blank lines in a row will be treated as a new paragraph so it might be hard to get three br's in a row.
