### ISSUE TITLE
Inline HTML

### ISSUE THREAD

**Issue by jkurei** [evilstreak/markdown-js#279]
Gruber's Markdown supports embedded HTML tags inside Markdown (https://daringfireball.net/projects/markdown/syntax#html), but this library just shows the HTML as plain text.

I understand this may not be an easy feature to implement, or at least not safely, but since it is a feature in Gruber's specification, README.md should warn this is not supported.

Example, using the example code in README.md:

<img width="413" alt="screen shot 2016-10-17 at 12 59 48" src="https://cloud.githubusercontent.com/assets/1428611/19435218/c9abfb6c-9469-11e6-9e46-2267084e584c.png">

(I'm not sure that span to change the color should work, but even ignoring the styling the HTML tag should no appear; that table definitely should work)

**Comment by urosjarc** [comment]
This feature is a **MUST**.

**Comment by ashb** [comment]
If someone writes this feature, and it has tests, and can be disabled in some manner then I'll happily merge it.

**Comment by sir-ragna** [comment]
Someone made a pull request for this. https://github.com/evilstreak/markdown-js/pull/98

**Comment by kpcyrd** [comment]
Please don't enable this by default, as you are probably introducing security issues for all your dependents if you do. 👎 

html in markdown is nice if you're the only person using it, but a complete disaster for applications using markdown to render comments like github does. And, no, "safe html" is just asking for somebody to come up with a clever way to break it.

**Comment by ashb** [comment]
Closing as duplicate of #98 where there's been more dicussion.
