### ISSUE TITLE
``` to <pre><code>?

### ISSUE THREAD

**Issue by TIGERB** [evilstreak/markdown-js#287]
For eample:

\```

\```
is interpreter to '\<p>\<code><\code><\p>' finnally 

but not the '\<pre>\<code><\code><\pre>';

why?

**Comment by ChrisZou** [comment]
+1

**Comment by xiguaaxigua** [comment]
+1

**Comment by nusje2000** [comment]
+1

**Comment by SelinaYu** [comment]
+1

**Comment by ashb** [comment]
This is not "stock" markdown but part of Github Flavoured markdown, which no one has opened a pull request for yet.

Duplicate of #41.
