### ISSUE TITLE
Link to `lib/markdown.js` not working in readme

### ISSUE THREAD

**Issue by danielpza** [evilstreak/markdown-js#301]
![image](https://user-images.githubusercontent.com/17787042/34118572-348fd556-e3ed-11e7-95f3-bb14635eb747.png)

![image](https://user-images.githubusercontent.com/17787042/34118599-4736d0e2-e3ed-11e7-9592-153caec53cae.png)

**Comment by danielpa9708** [comment]
The readme in github seems to work fine, maybe it's not updated in npm
