### ISSUE TITLE
Strikethrough component doesn't work.

### ISSUE THREAD

**Issue by stach** [evilstreak/markdown-js#302]
```javascript
markdown.toHTML("Strikethrough uses two tildes. ~~Scratch this.~~")
"<p>Strikethrough uses two tildes. ~~Scratch this.~~</p>"
```

It does not work.

It should've returned this :
> Strikethrough uses two tildes. ~~Scratch this.~~

**Comment by ashb** [comment]
Strikethrough is part of Github flavoured markdown, duplicate of #41
