### ISSUE TITLE
Add note to README that this repo is not maintained

### ISSUE THREAD

**Issue by ben-turner** [evilstreak/markdown-js#310]
Seeing as this repo doesn't seem to be maintained anymore, it would be very helpful to add a note to the top of the README about it (maybe including a listing of alternatives) or archive the repo. It's always frustrating to use a library, and once you're past the point of no return you find a bug, try to report it, and realize it will never get fixed. Seeing as this library gets almost 58K downloads per week and is the top google result for "node markdown", I would imagine that this has happened to quite a few people using this library.

This is still a great library though, so I'd hate for it to get deleted.

**Comment by dpierangeli** [comment]
Yes, i cannot agree more.

**Comment by ben-turner** [comment]
Created PR #312 for this.
