### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by x3rz** [evilstreak/markdown-js#317]
Hello Developers,
I have found a potential security vulnerability in your project that I reported on huntr.dev, as reports are confidential which, can only be seen by maintainers and researcher. so please visit and validate.
https://www.huntr.dev/bounties/1-evilstreak/markdown-js/

**Comment by ashb** [comment]
https://github.com/evilstreak/markdown-js#notice-unmaintained
