### ISSUE TITLE
Support for in-page links?

### ISSUE THREAD

**Issue by MrTrick** [evilstreak/markdown-js#73]
There are several specs and recommendations for doing in-page links in markdown.
None of them seem to work in this library, for either the Gruber or Maruku dialect.

```
### title ###    {#anch}
### title ###    {: #anch}
{#anch}
-----------
{: #anch}
-----------
<a id="anch"></a>
### title ### (expect an auto-created id from the title)
```

What do you suggest?

**Comment by traf** [comment]
Can you elaborate a little bit on how this works? I'm looking to add id's and/or classes to markdown headers.

My markdown portion of my gulpfile looks like this:

~~~~
gulp.task('fileinclude', function() {
  gulp.src(['app/src/*.html'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@file',
      filters: {
        markdown: markdown.parse
      }
    }))
});
~~~~

How would I go about adding this Maruku parser exactly? Thanks for the help.
